<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\scr\IS.API.Common\IS.API.Common.csproj" />
    <ProjectReference Include="..\IS.Application\IS.Application.csproj" />
    <ProjectReference Include="..\IS.Infrastructure\IS.Infrastructure.csproj" />
  </ItemGroup>

</Project>
